In [166]:
import pickle
import numpy as np

In [237]:
path_old = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h_old_delete_sister_coupled_to'

with open(f"{path_old}/WT_trajectory1_0.pkl", "rb") as f:
    data_old = pickle.load(f)


In [238]:
data_old['sister'][0].shape

(77,)

In [239]:
sum(data_old['sister'][400]!=-1)

16

In [248]:
unique_vals =  np.unique(data_old['sister'][200])
unique_vals, np.sum(data_old['sister'][200]!=-1),  len(unique_vals)

(array([  -1,  341,  533,  574,  627,  629,  670,  750, 1113, 1281, 1322,
        1357, 1478, 1552, 1583, 1635, 1668, 1673, 1733, 1822, 1860, 1875,
        1911, 1966, 2043, 2062, 2725, 2740, 2819, 2845, 2964], dtype=int32),
 30,
 31)

In [243]:
path_old_1 = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h_old'

with open(f"{path_old_1}/WT_trajectory1_0.pkl", "rb") as f:
    data_old_1 = pickle.load(f)


In [247]:
unique_vals =  np.unique(data_old_1['sister'][200])
unique_vals, np.sum(data_old_1['sister'][200]!=-1),  len(unique_vals)

(array([  -1,    1,  758, 1504, 2294, 3198], dtype=int32), 30, 6)

In [235]:
data_old['sister'][200]

array([  -1,   -1,  533,   -1,   -1,   -1,   -1,   -1,   -1, 2725, 1733,
         -1,   -1,  750,   -1,   -1, 1673,  629,   -1, 1875,  574,   -1,
         -1, 2819,   -1,   -1, 1822, 1478,   -1,   -1,  627,   -1,   -1,
         -1,  341, 1635,   -1, 1668,   -1,   -1,   -1,   -1,   -1, 2740,
         -1, 1113, 1322, 1281,   -1,   -1,   -1, 1552,   -1,   -1, 2062,
       1966,   -1, 1357, 2964, 2043, 1860,   -1,   -1, 1583,   -1, 2845,
         -1,   -1,  670,   -1,   -1, 1911,   -1,   -1,   -1,   -1,   -1],
      dtype=int32)

In [197]:
path_1 = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h'

with open(f"{path_1}/WT_trajectory1_0.pkl", "rb") as f:
    data_1 = pickle.load(f)

In [198]:
data_1['sister'][400], data_old['sister'][400]

(array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 3102,
          -1,   -1,   -1,   -1,   -1, 2357,  603,   -1,   -1,   -1,   -1,
          -1,  882,   -1,   -1, 1091, 3138,   -1,   -1, 1403,   -1,   -1,
          -1,  828, 2116,   -1,  336,   -1,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,   -1, 3057,   -1,   -1,   -1,   -1,   -1,   -1,  648,
         653,   -1,   -1,   89,   -1, 3189,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,  276,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1],
       dtype=int32),
 array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 1336,
          -1,   -1,   -1,   -1,   -1, 1678,  205,   -1,   -1,   -1,   -1,
          -1, 3130,   -1,   -1, 2161,  671,   -1,   -1,    1,   -1,   -1,
          -1, 2799, 2799,   -1, 2161,   -1,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,   -1,  949,   -1,   -1,   -1,   -1,   -1,   -1, 3130,
        2744,   -1,   -1,  865,   -1, 2799,   -1,   -1,   -1,   -1,   -1,
          -1,   

In [200]:
data_1['sister'][200]
sum(data_1['sister'][400]!=-1), sum(data_old['sister'][400]!=-1)

(16, 16)

In [206]:
unique_vals =  np.unique(data_1['sister'][200])
unique_vals, len(unique_vals), len(data_1['sister'][200])

(array([  -1,   86,  276,  338,  604,  648,  657,  831,  882,  933, 1090,
        1093, 1404, 1418, 1493, 1835, 1840, 1850, 1891, 1987, 2016, 2118,
        2357, 2600, 2711, 2847, 2940, 3057, 3101, 3141, 3189], dtype=int32),
 31,
 77)

In [207]:
unique_vals =  np.unique(data_old['sister'][200])
unique_vals, len(unique_vals), len(data_old['sister'][200])

(array([  -1,   27,  120,  196,  220,  263,  640,  686,  842,  944, 1226,
        1281, 1371, 1683, 1883, 2149, 2161, 2199, 2328, 2722, 2797, 2809,
        3121, 3198], dtype=int32),
 24,
 77)

In [132]:
len(data_1['lef'][-1])

81

In [2]:
path = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h'

with open(f"{path}/WT_trajectory1_0.pkl", "rb") as f:
    data_2 = pickle.load(f)

In [3]:
len(data_2['lef'][0])

0

In [4]:
sum(data_2['sister'][300]!=-1)
data_2['sister'][300]

array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 1084,
         -1,   -1,   -1,   -1,   -1, 3041, 2151,   -1,   -1,  830,   -1,
         -1, 2078,   -1,   -1,  433, 1384,   -1,   -1, 2990,   -1,   -1,
         -1, 1246, 2972,   -1, 2290,   -1,   -1,   -1,   -1,   -1,   -1,
         -1,   -1,  703,  774,   -1,   -1,   -1,   -1,   -1,   -1, 2356,
       1778,   -1, 1203, 1581,   -1, 1713,   -1,   -1, 1614,   -1,  107,
         -1,   -1, 2849,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1],
      dtype=int32)

In [6]:
sum(data_2['sister'][300]!=-1)

21