In [166]:
import pickle
import numpy as np

In [193]:
path_old = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h_old'

with open(f"{path_old}/WT_trajectory1_0.pkl", "rb") as f:
    data_old = pickle.load(f)


In [194]:
data_old['sister'][0].shape

(77,)

In [195]:
sum(data_old['sister'][400]!=-1)

16

In [196]:
unique_vals =  np.unique(data['sister'][400])
unique_vals, len(unique_vals)

(array([  -1,  146,  621,  784, 1010, 1109, 1512, 1911, 2227, 2547, 2763,
        2889, 3002, 3388, 4308, 4417, 4455, 4767, 4983, 5220, 5408, 5779,
        5854, 6157, 6248], dtype=int32),
 25)

In [197]:
path_1 = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h'

with open(f"{path_1}/WT_trajectory1_0.pkl", "rb") as f:
    data_1 = pickle.load(f)

In [198]:
data_1['sister'][400], data_old['sister'][400]

(array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 3102,
          -1,   -1,   -1,   -1,   -1, 2357,  603,   -1,   -1,   -1,   -1,
          -1,  882,   -1,   -1, 1091, 3138,   -1,   -1, 1403,   -1,   -1,
          -1,  828, 2116,   -1,  336,   -1,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,   -1, 3057,   -1,   -1,   -1,   -1,   -1,   -1,  648,
         653,   -1,   -1,   89,   -1, 3189,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,  276,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1],
       dtype=int32),
 array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 1336,
          -1,   -1,   -1,   -1,   -1, 1678,  205,   -1,   -1,   -1,   -1,
          -1, 3130,   -1,   -1, 2161,  671,   -1,   -1,    1,   -1,   -1,
          -1, 2799, 2799,   -1, 2161,   -1,   -1,   -1,   -1,   -1,   -1,
          -1,   -1,   -1,  949,   -1,   -1,   -1,   -1,   -1,   -1, 3130,
        2744,   -1,   -1,  865,   -1, 2799,   -1,   -1,   -1,   -1,   -1,
          -1,   

In [200]:
data_1['sister'][200]
sum(data_1['sister'][400]!=-1), sum(data_old['sister'][400]!=-1)

(16, 16)

In [206]:
unique_vals =  np.unique(data_1['sister'][200])
unique_vals, len(unique_vals), len(data_1['sister'][200])

(array([  -1,   86,  276,  338,  604,  648,  657,  831,  882,  933, 1090,
        1093, 1404, 1418, 1493, 1835, 1840, 1850, 1891, 1987, 2016, 2118,
        2357, 2600, 2711, 2847, 2940, 3057, 3101, 3141, 3189], dtype=int32),
 31,
 77)

In [207]:
unique_vals =  np.unique(data_old['sister'][200])
unique_vals, len(unique_vals), len(data_old['sister'][200])

(array([  -1,   27,  120,  196,  220,  263,  640,  686,  842,  944, 1226,
        1281, 1371, 1683, 1883, 2149, 2161, 2199, 2328, 2722, 2797, 2809,
        3121, 3198], dtype=int32),
 24,
 77)

In [132]:
len(data_1['lef'][-1])

81

In [2]:
path = '/Users/xcyan/Desktop/discrete_extrusion/02082025/tau10h/WT_alpha_100_tau_10h'

with open(f"{path}/WT_trajectory1_0.pkl", "rb") as f:
    data_2 = pickle.load(f)

In [3]:
len(data_2['lef'][0])

0

In [4]:
sum(data_2['sister'][300]!=-1)
data_2['sister'][300]

array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 1084,
         -1,   -1,   -1,   -1,   -1, 3041, 2151,   -1,   -1,  830,   -1,
         -1, 2078,   -1,   -1,  433, 1384,   -1,   -1, 2990,   -1,   -1,
         -1, 1246, 2972,   -1, 2290,   -1,   -1,   -1,   -1,   -1,   -1,
         -1,   -1,  703,  774,   -1,   -1,   -1,   -1,   -1,   -1, 2356,
       1778,   -1, 1203, 1581,   -1, 1713,   -1,   -1, 1614,   -1,  107,
         -1,   -1, 2849,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1],
      dtype=int32)

In [6]:
sum(data_2['sister'][300]!=-1)

21